title: Prompt an Image Generator
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: What you will make
  - title: Prompt an Image Generator
  - title: What next?
